### PR TITLE
Add userpref to choose anaglyph type

### PR DESCRIPTION
**Pull request by Alexey-Akishin**
Option to choose anaglyph type becomes visible only when user chooses "Anaglyph" as 3D display mode.

### CODE REVIEW

**Comment by dfelinto** [comment]
I think we may not need that many modes, specially USER_ANAGLYPH_TYPE_GREEN_MAGENTA and USER_ANAGLYPH_TYPE_MAGENTA_GREEN (why do we need both?).

But for now it's fine, we can do cleanups later. Thanks for the pull

**Comment by dfelinto** [comment]
I think it's better without. if someone claims she can't use some particular glasses we then can pull it back in.
anaglyph for Image Editor (which will be the base for the other 3-D friendly editors).

A preview of what I'm planning to commit next:
https://twitter.com/dfelinto/status/336397293051850752/photo/1

**Comment by Alexey-Akishin** [comment]
OK then, I sent pull request to remove Magenta-Green. You are probably right, there is no point to support this rare anaglyph scheme unless somebody needs it.

You are doing great work, it will be nice to see stereo anaglyph in image editor. But the picture in your preview requires Cyan-Red glasses instead of Red-Cyan.

**Comment by dfelinto** [comment]
look at the code now. You can go ahead and implement the other anaglyph colors.
as for cyan-red VS red-cyan you may be right. feel free to fix otherwise I will tackle it later.

I notice my side-by-side may be reverted as well.
screen shot 2013-05-20 at 8 10 36 pm

I think it's because I'm rendering the images in the wrong order. again, it should be a piece of cake to fix. I coded in a bit of a rush (laptop went out of battery ;)

**Comment by dfelinto** [comment]
Something that would be nice to code next (and you are welcome to contribute to) is a system in the Viewport that mimics what I'm doing for the Image Editor.

See the changes in wm_draw.c , the iuser->eye setup. It would be nice to have a way to preview the multiview cameras in the viewport (and if we do, the SCREEN_OT_screen_clean_full_area operator could be updated to support the viewport as well (basically uncomment the code that is there).

**Comment by Alexey-Akishin** [comment]
Thanks. Hopefully by tomorrow I will have some patches.

**Comment by Alexey-Akishin** [comment]
I have implemented support for all anaglyph schemes in wm_stereo.c. Fixed problem with red-cyan, tested green-magenta, works as expected.

Your side-by-side is correct: when watching side-by-side left eye will see right picture and vice-versa. I rendered a cube and in side-by-side mode I can see stereo image without glasses. Great! There is two problems with this mode however: everything is horizontally distorted (compressed) and using mouse cursor is hard, feels like Blender does not "understand" that it has double UI when in side-by-side mode.

**Comment by Alexey-Akishin** [comment]
Regarding previewing multiview cameras in viewport. Tomorrow I will try to make UI for this and I will show it to you, to make sure it's good enough. After getting UI ready, I can try to implement this feature...

**Comment by dfelinto** [comment]
"Your side-by-side is correct: when watching side-by-side left eye will see right picture and vice-versa. I rendered a cube and in side-by-side mode I can see stereo image without glasses."

To see without glasses you indeed need the views crossed. For glasses, however you need left-right (I'm almost sure of that). So I changed that.

"There is two problems with this mode however: everything is horizontally distorted (compressed)"
That's a known limitation of the format. As far as I know that's how it is (and that's why passive domestic TVs/displays are only half the resolution they claim to be).

"And using mouse cursor is hard, feels like Blender does not "understand" that it has double UI when in side-by-side mode."
That has to be tested in a real monitor, the clicking area is correct I believe. I suspect that it will work nicely. The problem is where the mouse shows up - it may need to be rendered twice distorted as well.

**Comment by Alexey-Akishin** [comment]
Changing eye order inverted anaglyph modes, so I sent a fix.

Yes, it seems you are correct, for viewing side-by-side with glasses left picture must be on the left.

Regarding mouse cursor, ideally yes, it needs to be rendered twice for side-by-side mode, currently it does not work as expected without special setup.

I think we need some settings for side-by-side mode. I looked at available settings for side-by-side 3D in youtube, and following setting are available there: "half-width" (this is what we currently have), "full-width" (not distorted, but rendered at quarter resolution), "swap (right-left)". For example, for using side-by-side mode with prismatic glasses on normal monitor usually full-width mode is needed; it's also needed for cross-eyed viewing method. I could try to implement these options in near future for side-by-side mode. Working in full color stereo on normal monitor sounds tempting (even at quarter resolution - not so bad on big monitor, but I probably have to purchase prismatic glasses for better comfort).

**Comment by Alexey-Akishin** [comment]
Of course in case of Blender (unlike YouTube), it would be possible to use non-distorted side-by-side mode at half resolution as well, it will be similar to what we have as side-by-side mode in Blender Game Engine (so if user decides to preserve original aspect ratio of the screen and work at quarter resolution, he/she can just work in horizontally maximized window and adjust window height as desired). But first I will work on multiview camera preview in viewport.

**Comment by Alexey-Akishin** [comment]
This is an example how UI for previewing multiview cameras could look like:
multiview
If in the viewport there is no active multiview camera or there is less than 2 multiview cameras enabled in the scene, this drop-down list will not be visible. In the future more multiview viewport settings could be added in the multiview panel. Please let me know what you think about this idea.

**Comment by dfelinto** [comment]
1) I'm not convinced of the need for non-compressed side-by-side. Maybe I'm just not considering "prismatic glasses", but are they for real? would someone use one in production? Same for cross-eyes. It's trivial to implement but if we go this route we will also have to support mirrored images (which is my favourite low/non budget 3-D mode btw) and other not so popular methods.

I would suggest we stick to the formats being used by the industry now, and from there we assist the need for more modes.

2) For viewport: we need a toggle to entirely disable the Multiview in the viewport. So the user can quickly switch between the active camera, and one of the views. Apart from that I think it's good. Technically 3-D should be available only when we have "left" and "right", but for now it's fine to follow how we are doing in the Image Editor.
(I will create a new "issue" to discuss other pending issues)

**Comment by Alexey-Akishin** [comment]
1) Cross-eyed method can be good enough for viewing stereo 3D images or animations, especially if side-by-side picture (Blender window) is small; but it's usually not good for prolonged use without rest, and some people cannot use it at all. Unlike cross-eyed method, prismatic glasses are relatively comfortable for eyes, some glasses have an option to hide unwanted "ghost" side images, to help to focus on 3D image. So prismatic glasses solve 1 or 2 most noticeable drawbacks of cross-eyed viewing method. They still have drawbacks of course, but it's inexpensive method to view stereo 3D in full color on normal 60Hz computer monitor. In case you are interested how prismatic glasses work, this article explains it: http://www.vrtifacts.com/build-your-own-fluid-based-prismatic-stereoscopic-goggles/ . Commercially available prismatic glasses exist, for example Glascope; on Amazon more models could be found.
2) OK, I think I understand. Hopefully I will have a patch in next few days.

**Comment by dfelinto** [comment]
1) I will send an email to bf-committers to gather some feedback on which displays modes to support.

2) As for viewport, we don't need a toggle anymore. I think the "D" shortcut should be enough (it sets a flag in the window). As for 3-D only being available when we have left and right, we can have something similar to RE_HasStereo3D (but taking the active SceneRenderViews into account).

While at it, I think it may be better to not have the UI you are proposing ... Blender already has ways to switch between the cameras, not sure we want to add on top of that.

So wrapping up: [a] no UI at first, shows 3-D in viewport if:

((wmWindow.flag & WM_STEREO) && (U.stereodisplay != USER_STEREO_DISPLAY_NONE) && (hasrightviewactive && hasleftviewactive)

3) Also I added you as a collaborator so you can assign issues to yourself (and eventually close them).

But for coding (specially because I use the same repo for other projects/branchs - the oceanviz) let's stick to pull requests, ok?

/me still learning my ways into github

**Comment by dfelinto** [comment]
(I'm copying the viewport part of the discussion to a new issue that I will assign to you)

**Comment by Alexey-Akishin** [comment]
On Friday 24 May 2013 09:55:49 Dalai Felinto wrote:
1) It seems I'm not the only one who wants non-commpressed option for side-by-side view. I'm thinking about adding checkbox "Full width" for side-by-side mode. I'm sure I will use it at least occasionally, and I believe some other people will use it too.
3) OK.

**Pull request merged**
